# Generated by Django 4.2.11 on 2026-04-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('searching', 'Searching Web'), ('reading', 'Reading Sources'), ('summarizing', 'Summarizing Content'), ('generating', 'Generating Report'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('search_results', models.JSONField(blank=True, default=list)),
                ('sources_text', models.JSONField(blank=True, default=list)),
                ('summaries', models.JSONField(blank=True, default=list)),
                ('report', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
